# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3bafeea6-2e45-4048-b192-436b5a8f4e3b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/f57eea7e-69d2-4629-af51-0fbff1e1a807";
      fsType = "ext2";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6488f5b6-9412-4c35-9f1d-ae7bc442410e"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
